# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=30000
SAVEHIST=1000
setopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/{{ user.name }}/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export TERM="xterm-256color"
export JAVA_HOME=/usr/lib/jvm/default
alias vi="vim"
alias keypassfiler="sudo mount -t cifs //Filer17L/IT170L/ /mnt/filer17 -o user=e513906,uid=cbaer"
alias windowsshare="vmhgfs-fuse -o auto_unmount .host:/share-vm /home/cbaer/win-share"
alias sbb="cd ~/work/sbb"
export VISUAL=vim
export EDITOR=vim

COMPLETION_WAITING_DOTS="true"
HIST_TIMESTAMP="yyyy-mm-dd"

bindkey "[C" forward-word
bindkey "[D" backward-word

export ZSH=$HOME/.oh-my-zsh

#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  oc git docker
)

if [[ $DISPLAY ]]; then
  # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
else
  ZSH_THEME="clean"
fi

source $ZSH/oh-my-zsh.sh
