---

- name: setup
  hosts: localhost

  tasks:
    - include_role:
        name: setup
    - include_role:
        name: desktop
    - include_role:
        name: extras
    - include_role:
        name: zsh