---

- name: setup
  hosts: localhost

  roles:
    - setup
#    - desktop

- name: run as local user
  hosts: localhost
  remote_user: "{{ user.name }}"

  tasks:
    - name: install yay
      include_role:
        name: setup
        tasks_from: yay
 # roles:
 #   - postdesktop
 #   - zsh

