---
- name: Install sytemcomponents, desktop and tooling
  hosts: localhost

  tasks:
    - name: Install system components
      ansible.builtin.include_role:
        name: systemcomponents

    - name: Install desktop
      ansible.builtin.include_role:
        name: desktop

    - name: Install and configure tools
      ansible.builtin.include_role:
        name: tooling

    - name: Install components for virutal environment
      ansible.builtin.include_role:
        name: virtualization
      when: is_vm

    - name: Finalize be setting sudoers file correct
      ansible.builtin.include_role:
        name: finalize
