---
- name: install plasma kde
  become: yes
  shell: pacman --noconfirm -S plasma-meta

- name: install additional plasma tools
  become: yes
  shell: pacman --noconfirm -S konsole dolphin kate kdeplasma-addons

- name: install additional fonts
  shell: yay --noconfirm -S ttf-dejavu ttf-roboto noto-fonts-emoji

- name: install gui tools
  shell: yay --noconfirm -S google-chrome keepassxc rambox-bin thunderbird meld

- name: copy kwalletrc
  copy:
    src: kwalletrc
    dest: "/home/{{ user.name }}/.config/kwalletrc"
