- name: install xorg server
  shell: yay -S --noconfirm xorg xorg-xinit xorg-server mesa xorg-twm xterm xorg-xclock xf86-input-synaptics xorg-drivers

- name: copy xinit start file for plasma
  copy:
    src: .xinitrc-plasma
    dest: /home/cbaer/.xinitrc
  tags: plasma

- name: install plasma kde
  shell: yay -S --noconfirm plasma-meta
  tags: plasma

- name: install additional plasma tools
  shell: yay -S --noconfirm konsole dolphin google-chrome kate terminator kdeplasma-addons
  tags: plasma

- name: copy xinit start file for cinnamon
  copy:
    src: .xinitrc-cinnamon
    dest: /home/cbaer/.xinitrc
  tags: cinnamon

- name: install cinnamon
  shell: yay -S --noconfirm cinnamon nemo-fileroller
  tags: cinnamon

- name: install cinnamon applications
  shell: yay -S --noconfirm  xed xviewer xreader xplayer pix faenza-icon-theme numix-gtk-theme
  tags: cinnamon

- name: install vmwaretools
  shell: yay -S --noconfirm open-vm-tools xf86-input-vmmouse xf86-video-vmware gtkmm3

- name: enable and start vmwaretools
  become: yes
  service:
    name: vmtoolsd
    state: started
    enabled: yes

- name: copy xwrapper config
  become: yes
  copy:
    src: Xwrapper.config
    dest: /etc/X11/Xwrapper.config