---
- name: Set hostname
  ansible.builtin.template:
    src: hostname
    dest: /etc/hostname
    owner: root
    group: root
    mode: "u=rw,g=rw,o=r"

- name: Set hosts file
  ansible.builtin.template:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: "u=rw,g=rw,o=r"
