---
- name: Create timezone file
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: Set hardwareclock
  ansible.builtin.shell: hwclock --systohc --utc
  register: output
  changed_when: output.rc == 0

- name: Set locale
  ansible.builtin.locale_gen:
    name: "{{ locale }}"
    state: present

- name: Create locale conf
  ansible.builtin.lineinfile:
    path: /etc/locale.conf
    line: "LANG={{ locale }}"
    create: yes

- name: Keymap
  ansible.builtin.lineinfile:
    path: /etc/vconsole.conf
    line: "KEYMAP={{ keymap }}"
    create: yes

- name: Set LC_ALL locale
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      LC_ALL=en_US.UTF-8
      LANG=en_US.UTF-8
