---
- name: Disable pc speaker
  ansible.builtin.template:
    src: nobeep.conf
    dest: /etc/modprobe.d/nobeep.conf
    owner: root
    group: root
    mode: "u=rw,g=rw,o=r"

- name: Install packages
  ansible.builtin.command: "pacman --noconfirm -S python os-prober"
  register: pacmaninstall
  changed_when: pacmaninstall.rc == 0

- name: Create keyring
  ansible.builtin.include_tasks:
    file: keyring.yaml

- name: Create network
  ansible.builtin.include_tasks:
    file: network.yaml

- name: Install ssh
  ansible.builtin.include_tasks:
    file: ssh.yaml

- name: Create locale
  ansible.builtin.include_tasks:
    file: locale.yaml

- name: Create hostname
  ansible.builtin.include_tasks:
    file: hostname.yaml

- name: Create users
  ansible.builtin.include_tasks:
    file: users.yaml

- name: Update ntp
  ansible.builtin.include_tasks:
    file: ntp.yaml

- name: Update linux-kernel
  ansible.builtin.include_tasks:
    file: linux_kernel.yaml
