---
- name: Install ntp
  ansible.builtin.command: pacman --noconfirm -S ntp
  register: pminstall
  changed_when: pminstall.rc == 0

- name: Configure swiss metas atomic clocks
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: "root"
    group: "root"
    mode: "u=rw,g=rw,o=r"

- name: Make sure ntpd is stopped
  ansible.builtin.service:
    name: ntpd
    state: stopped
    enabled: true

- name: Sync time with swiss ntp metas atomic clock
  ansible.builtin.command: ntpdate ntp11.metas.ch
  register: ntpdateoutput
  changed_when: ntpdateoutput.rc == 0

- name: Sync time to hwclock
  ansible.builtin.command: hwclock --systohc
  register: hwclockoutput
  changed_when: hwclockoutput.rc == 0
