---
- name: Install ntp
  ansible.builtin.command: pacman --noconfirm -S ntp
  register: pacmaninstall
  changed_when: pacmaninstall.rc == 0

- name: Configure swiss metas atomic clocks
  ansible.builtin.template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: "root"
    group: "root"
    mode: "u=rw,g=rw,o=r"

- name: Make sure ntpd is stopped
  ansible.builtin.service:
    name: ntpd
    state: stopped
    enabled: true

- name: Sync time with swiss ntp metas atomic clock
  ansible.builtin.command: ntpdate ntp11.metas.ch
  register: ntpdate
  changed_when: ntpdate.rc == 0

- name: Sync time to hwclock
  ansible.builtin.command: hwclock --systohc
  register: hwclock
  changed_when: hwclock.rc == 0
