- name: install vmtool packages
  shell: pacman --noconfirm -S open-vm-tools gtkmm3

- name: enable vmtools and vmware-fuse
  shell: "systemctl enable {{ servicename }}"
  loop:
    - vmtoolsd.service
    - vmware-vmblock-fuse.service
  loop_control:
    loop_var: servicename

- name: add vmware modules in mkinitcpio.conf
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: 'MODULES=( vmw-balloon vmw_pvscsi vmw_vmci vmwgfx vmxnet3 vsock vmw_vsock_vmci_transport)'
