---
- name: Install yay
  ansible.builtin.import_tasks:
    file: yay.yaml

- name: Update Cache
  ansible.builtin.import_tasks:
    file: update_cache.yaml

- name: Setup pulseaudio
  ansible.builtin.import_tasks:
    file: pulseaudio.yaml

- name: Add audiocodecs
  ansible.builtin.import_tasks:
    file: audiocodecs.yaml

- name: Configure vim
  ansible.builtin.import_tasks:
    file: vim.yaml

- name: Install systemtools
  ansible.builtin.import_tasks:
    file: systemtools.yaml

- name: Install zsh
  ansible.builtin.import_tasks:
    file: zsh.yaml

- name: Update kernelmodules
  ansible.builtin.import_tasks:
    file: update_kernelmodules.yaml
