---
# the drivers are mainly hosted by commiunity project so they have to be
# installed via yay
# shell has to be used because the command module does not allow to
- name: Install drivers # noqa command-instead-of-shell
  ansible.builtin.shell: yay --noconfirm -S aic94xx-firmware wd719x-firmware upd72020x-fw linux-firmware-qlogic
  register: pminstall
  changed_when: pminstall.rc == 0

- name: Build kernel
  become: true
  ansible.builtin.command: mkinitcpio -p linux
  register: mkinitcpio
  changed_when: mkinitcpio.rc == 0
