---
- name: Install zsh
  ansible.builtin.command: yay --noconfirm -S zsh zsh-syntax-highlighting ttf-meslo-nerd-font-powerlevel10k
  register: yay
  changed_when: yay.rc == 0

- name: Modify shell for user
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - "{{ user.name }}"
    - root

- name: Clone oh-my-zsh # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ user.name }}/.oh-my-zsh"

- name: Clone powerlevel10k # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/{{ user.name }}/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Copy zshrc
  ansible.builtin.template:
    src: zshrc
    dest: "/home/{{ user.name }}/.zshrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rw,g=r,o=r"

- name: Copy powerlevel10k config
  ansible.builtin.copy:
    src: p10k.zsh
    dest: "/home/{{ user.name }}/.p10k.zsh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rw,g=r,o=r"

- name: Clone oh-my-zsh for root # noqa latest[git]
  become: true
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /root/.oh-my-zsh

- name: Copy zshrc for root
  become: true
  ansible.builtin.copy:
    src: zshrc_root
    dest: /root/.zshrc
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
