---
- name: install kitty
  shell: yay -S --noconfirm kitty

- name: set kitty config
  copy:
    src: kitty.conf
    dest: /home/cbaer/.config/kitty/

- name: install drivers
  shell: yay -S --noconfirm aic94xx-firmware wd719x-firmware upd72020x-fw linux-firmware-qlogic

- name: regenerate initramfs
  become: yes
  command: "mkinitcpio -p linux"

- name: install system tools
  shell: yay -S --noconfirm cifs-utils cpio nfs-utils gcc gcc-libs glances gzip htop inetutils jdk openssh rpmextract sshpass unzip wget zip

- name: install additional fonts
  shell: yay -S --noconfirm ttf-dejavu ttf-roboto noto-fonts-emoji

- name: install dev tools
  shell: yay -S --noconfirm ansible docker git meld

- name: install work tools
  shell: yay -S --noconfirm google-chrome keepassxc rambox-bin thunderbird
