---
- name: create global git config
  become: yes
  template:
    src: .gitconfig
    dest: "/home/{{ user.name }}/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rw,g=r,o=r"