---
- name: install kitty
  become: yes
  shell: pacman --noconfirm -S kitty

- name: set kitty config
  copy:
    src: kitty.conf
    dest: "/home/{{ user.name }}/.config/kitty/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rw,g=r,o=r"