---
- name: Install visual studio code
  ansible.builtin.command: yay --noconfirm -S visual-studio-code-bin
  register: yay
  changed_when: yay.rc == 0

- name: Install visual studio code plugins
  ansible.builtin.command: code --install-extension "{{ item }}"
  register: code
  changed_when: code.rc == 0
  loop:
    - equinusocio.vsc-material-theme
    - equinusocio.vsc-material-theme-icons
    - equinusocio.vsc-community-material-theme
    - mohsen1.prettify-json
    - nobuhito.printcode
    - yzhang.markdown-all-in-one
    - wholroyd.jinja
    - ivory-lab.jenkinsfile-support
    - eamodio.gitlens
    - redhat.ansible
    - dotjoshjohnson.xml

- name: Ensure vsc config directory exists
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.config/Code/User"
    state: directory
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rwx,g=rwx,o=rx"

- name: Update vsc config
  become: true
  ansible.builtin.copy:
    src: settings.json
    dest: "/home/{{ user.name }}/.config/Code/User"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rw,g=r,o=r"
