---
- name: install visual studio code
  shell: yay --noconfirm -S visual-studio-code-bin

- name: install visual studio code plugins
  command: "code --install-extension {{ item }}"
  with_items:
    - davidanson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - equinusocio.vsc-material-theme
    - equinusocio.vsc-material-theme-icons
    - equinusocio.vsc-community-material-theme
    - mohsen1.prettify-json
    - nobuhito.printcode
    - yzhang.markdown-all-in-one
    - wholroyd.jinja
    - ivory-lab.jenkinsfile-support
    - eamodio.gitlens
    - dotjoshjohnson.xml

- name: update vsc config
  copy:
    src: settings.json
    dest: "/home/{{ user.name }}/.config/Code/User"
