---
- name: install visual studio code
  shell: yay --noconfirm -S visual-studio-code-bin

- name: install visual studio code plugins
  command: "code --install-extension {{ item }}"
  with_items:
    - davidanson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - equinusocio.vsc-material-theme
    - equinusocio.vsc-material-theme-icons
    - equinusocio.vsc-community-material-theme
    - mohsen1.prettify-json
    - nobuhito.printcode
    - yzhang.markdown-all-in-one
    - wholroyd.jinja
    - ivory-lab.jenkinsfile-support
    - eamodio.gitlens
    - dotjoshjohnson.xml

- name: ensure vsc config directory exists
  become: yes
  file:
    path: "/home/{{ user.name }}/.config/Code/User"
    state: directory
    recurse: yes
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rwx,g=rx,o=rx"

- name: update vsc config
  become: yes
  copy:
    src: settings.json
    dest: "/home/{{ user.name }}/.config/Code/User"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "u=rw,g=r,o=r"
