---
- name: set hostname
  template:
    src: hostname
    dest: /etc/hostname
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: set hosts file
  template:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"