---
- name: create timezone file
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: set hardwareclock
  shell: hwclock --systohc --utc

- name: set locale
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: locale.conf
  lineinfile:
    path: /etc/locale.conf
    line: "LANG={{ locale }}"
    create: yes

- name: keymap
  lineinfile:
    path: /etc/vconsole.conf
    line: "KEYMAP={{ keymap }}"
    create: yes

- name: set LC_ALL locale
  blockinfile:
    path: /etc/environment
    block: |
      LC_ALL=en_US.UTF-8
      LANG=en_US.UTF-8