---
- import_tasks: keyring.yaml
- import_tasks: locale.yaml
- import_tasks: users.yaml
- import_tasks: hostname.yaml
#- import_tasks: yay.yaml
#  remote_user: "{{ user.name }}"
#- import_tasks: linux_kernel.yaml
#- import_tasks: ntp.yaml
#- import_tasks: pulseaudio.yaml
#- import_tasks: vim.yaml
#- import_tasks: kitty.yaml