---
- name: install system tools
  shell: pacman -S --noconfirm cifs-utils cpio nfs-utils gcc gcc-libs glances gzip htop inetutils rpmextract sshpass unzip wget zip arandr bluez bluez-utils net-tools docker