---
- name: create user
  user:
    name: "{{ user.name }}"
    password: "{{ user.password | password_hash('sha512') }}"
    groups: wheel

- name: modify wheel entry
  lineinfile:
    path: /etc/sudoers
    regexp: '^# %wheel ALL=(ALL:ALL) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'

- name: set password root User
  user:
    name: root
    password: "{{ root.password | password_hash('sha512') }}"