---
- name: remove build directory
  become: yes
  file:
    path: /tmp/yay
    state: absent

- name: clone yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay

- name: build yay
  shell: |
    cd /tmp/yay
    makepkg -si --noconfirm

- name: remove build directory
  become: yes
  file:
    path: /tmp/yay
    state: absent