---
- name: clone yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/git/yay

- name: build yay
  become: "{{ user.name }}"
  shell: |
    cd /tmp/git/yay
    makepkg -si --noconfirm

- name: remove build directory
  file:
    path: /tmp/git/yay
    state: absent