---
- name: modify shell for user
  become: yes
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - "{{ username }}"
    - root

- name: update Datetime
  become: yes
  command: timedatectl set-ntp true

- name: delete existing directory
  become: yes
  file:
    path: /tmp/git
    state: absent

- name: recreate directory
  file:
    path: /tmp/git
    state: directory

- name: recreate directory
  become: yes
  file:
    path: /usr/share/ansible
    state: directory

- name: clone ansible-yay library
  git:
    repo: 'https://github.com/mnussbaum/ansible-yay.git'
    dest: /tmp/git/ansible-yay

- name: copy yay-library to default ansible location
  become: yes
  file:
    path: /tmp/git/ansible-yay/yay
    dest: /usr/share/ansible

- name: Create ANSIBLE_LIBRARY environment variable
  become: yes
  lineinfile:
    path: /etc/environment
    line: "ANSIBLE_LIBRARY=/usr/share/ansible"

- name: clone yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/git/yay

- name: build yay
  shell: |
    cd /tmp/git/yay
    makepkg -si --noconfirm

- name: clone oh-my-zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: /home/cbaer/.oh-my-zsh 

- name: copy pacman mirrorlist
  become: yes
  copy:
    src: pacman-mirrorlist
    dest: /etc/pacman.d/mirrorlist

- name: update cache
  yay:
    update-cache: yes

- name: Install ntp daemon
  become: yes
  yay:
    name: ntp
    state: present
  register: install
  until: install is success
  retries: 10
  delay: 2

- name: Configure swiss metas atomic clocks
  become: yes
  copy:
    src: ntp.conf 
    dest: /etc/

- name: Make sure ntpd is stopped
  become: yes
  service:
    name: ntpd
    state: stopped
    enabled: yes

- name: Sync time with swiss ntp metas atomic clock
  become: yes
  shell: ntpdate metasntp11.admin.ch

- name: Start ntpd back up
  become: yes
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Sync time to hwclock
  become: yes
  shell: hwclock --systohc

- name: install additional tools
  yay:
    name: "{{ item }}"
    state: latest
  with_items:
    - aic94xx-firmware
    - ansible
    - bash-completion
    - byobu
    - docker
    - dolphin
    - firefox
    - fontconfig
    - gcc
    - gcc-libs
    - git
    - glances
    - google-chrome
    - gzip
    - htop
    - jdk
    - keepassxc
    - meld
    - networkmanager
    - net-tools
    - openssh
    - open-vm-tools
    - plasma
    - plymouth
    - rambox
    - spotify
    - terminator
    - thunderbird
    - tmux
    - ttf-dejavu
    - unzip
    - visual-studio-code-bin
    - wd719x-firmware
    - wget
    - xorg
    - xorg-server
    - xorg-xinit
    - xorg-drivers
    - networkmanager
    - zip
    - zsh-completions
    - zsh-syntax-highlighting

- name: create fonts directory
  become: yes
  file:
    path: /usr/share/fonts/opentype
    state: directory
    mode: '0755'

- name: Download fonts 
  become: yes
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/DroidSansMono.zip
    dest: /usr/share/fonts/opentype/DroidSansMono.zip

- name: Extract font
  become: yes
  unarchive:
    src: /usr/share/fonts/opentype/DroidSansMono.zip
    dest: /usr/share/fonts/opentype/
    remote_src: yes

- name: reload font cache
  become: yes
  command: fc-cache -v -f

- name: update OS
  yay:
    update_cache: yes
    upgrade: yes

- name: regenerate initramfs
  become: yes
  command: "mkinitcpio -p linux"

- name: configure plymouth
  become: yes
  command: "plymouth-set-default-theme -R spinfinity"

- name: create powerlevel9k theme directory
  file:
    path: '/home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel9k'
    state: directory

- name: clone powerlevel9k repository
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: '/home/{{ username }}/.oh-my-zsh/custom/themes/powerlevel9k'

- name: copy zshrc
  copy:
    src: zshrc
    dest: '/home/{{ username }}/.zshrc'

- name: copy zshrc-desktop
  copy:
    src: zshrc-desktop
    dest: '/home/{{ username }}/.zshrc-desktop'

- name: create terminator config dir
  file:
    path: '/home/{{ username }}/.config/terminator'
    state: directory

- name: copy terminator config
  copy:
    src: terminator-config
    dest: '/home/{{ username }}/.config/terminator/config'

- name: copy pacman config
  become: yes
  copy:
    src: pacman.conf
    dest: /etc

- name: copy vimrc
  copy:
    src: vimrc
    dest: '/home/{{ username }}/.vimrc'

- name: create vim colors directory
  file:
    path: '/home/{{ username }}/.vim/colors'
    state: directory

- name: download jelly beans
  get_url:
    url: https://raw.githubusercontent.com/nanotech/jellybeans.vim/master/colors/jellybeans.vim
    dest: '/home/{{ username }}/.vim/colors/'

- name: copy kwalletrc
  copy:
    src: kwalletrc
    dest: '/home/{{ username }}/.config/kwalletrc'

- name: install vsc plugins
  command: "code --install-extension {{ item }}"
  with_items:
    - davidanson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - pkief.material-icon-theme
    - equinusocio.vsc-material-theme
    - mohsen1.prettify-json

- name: update vsc config
  copy:
    src: settings.json
    dest: '/home/{{ username }}/.config/Code/User'

- name: set x11-keymap for apple
  become: yes
  command: localectl set-x11-keymap ch apple de_mac
  when: keyboardlayout == 'apple'

- name: set x11-keymap for dell
  become: yes
  command: localectl set-x11-keymap ch dell de_nodeadkeys
  when: keyboardlayout == 'dell'

- name: set language
  become: yes
  command: localectl set-locale LANG=en_US.UTF-8

- name: set keymap
  become: yes
  command: localectl set-keymap de_CH-latin1

#- name: set xkbmap
#  become: yes
#  command: setxkbmap -model apple -layout ch -variant de_mac
#  when: keyboardlayout == 'apple'

- name: enable and start networkmananger
  become: yes
  service:
    name: NetworkManager
    state: started
    enabled: yes

- name: enable and start vmwaretools
  become: yes
  service:
    name: vmtoolsd
    state: started
    enabled: yes

- name: copy xinitrc file
  copy:
    src: xinitrc
    dest: '/home/{{ username }}/.xinitrc'